// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhaQIhdVqV2zjN7h30HucNiuRtJYLw6LU',
    appId: '1:28548170816:web:48069161bbd3970eb50ba5',
    messagingSenderId: '28548170816',
    projectId: 'ecapp-15c90',
    authDomain: 'ecapp-15c90.firebaseapp.com',
    storageBucket: 'ecapp-15c90.firebasestorage.app',
    measurementId: 'G-J867F3EEB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5g0CVyAxOTYPWYp_nSJCvRE2leFHyv-o',
    appId: '1:28548170816:android:7e86f43aa6e7cedfb50ba5',
    messagingSenderId: '28548170816',
    projectId: 'ecapp-15c90',
    storageBucket: 'ecapp-15c90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkwV_1WIcrD_kOSBnc87aZvcfACJv4r3g',
    appId: '1:28548170816:ios:a15af48286b8c386b50ba5',
    messagingSenderId: '28548170816',
    projectId: 'ecapp-15c90',
    storageBucket: 'ecapp-15c90.firebasestorage.app',
    iosBundleId: 'com.example.ecapp',
  );
}
